---
- name: Provisioning Redmine
  hosts: app
  become: true

  pre_tasks:
  # begin MYSQL specific
  - name: Connection URL
    set_fact:
      DATABASE_URL: "mysql://{{ db_user }}:{{ db_password }}@127.0.0.1:3306/{{ db_name }}"
  # end MYSQL specific

  - user:
      name: "{{ app_user }}"
      groups: "www-data"

  roles:
  #- dresden-weekly.Rails/postgresql # POSTGRESQL specific

  # begin MYSQL specific
  - role: geerlingguy.mysql
    mysql_bind_address: "127.0.0.1"
    mysql_root_password: "mysql"
    mysql_databases:
    - name: "{{ db_name }}"
    mysql_users:
    - name: "{{ db_user }}"
      password: "{{ db_password }}"
      priv: "{{ db_name }}.*:ALL"
  # end MYSQL specific

  - dresden-weekly.Rails/ruby/rvm
  #- dresden-weekly.Rails/ruby/postgresql # POSTGRESQL specific
  - dresden-weekly.Rails/ruby/mysql # MYSQL specific
  - dresden-weekly.Rails/ruby/sqlite3

  - dresden-weekly.Rails/rails/folders
  - dresden-weekly.Rails/rails/logrotate

  - role: dresden-weekly.Rails/user/profile
    rails_user_name: "{{ app_user }}"
    rails_user_bashrc_lines:
      - "cd {{ RAILS_APP_BASE_PATH }} || true"
      - "cd {{ RAILS_APP_CURRENT_PATH }} || true"
    rails_user_env:
      RAILS_ENV: "{{ rails_env }}"
      SECRET_KEY_BASE: "{{ app_secret_key_base }}"
      RAILS_LOG_FILE_PATH: "{{ RAILS_APP_LOG_PATH }}"
      DATABASE_URL: "{{ DATABASE_URL }}"

  - dresden-weekly.Rails/apache/server
  - dresden-weekly.Rails/apache/passenger

  - hicknhack-software.redmine/rmagick

  - role: hicknhack-software.redmine/apache/auth
    tags:
    - redmine_auth

  - role: hicknhack-software.redmine/apache/git
    tags:
    - redmine_auth

  - role: hicknhack-software.redmine/apache/subversion
    tags:
    - redmine_auth

  post_tasks:
  - name: create redmine link
    file:
      path: "{{ site_path }}"
      src: "{{ RAILS_APP_CURRENT_PUBLIC_PATH }}"
      state: link
      force: yes

- include: deploy.yml
  vars:
    provisioned: yes
